Repository bookingcom/shipper, pull requests merged in 2019-09, with the labels that each got.

#171 More CI tweaks
  Makefile
  ci/e2e.sh
  ci/test.sh
  hack/generate-groups.sh
  hack/update-codegen.sh
  kubernetes/shipper-state-metrics.deployment.yaml
  kubernetes/shipper.deployment.yaml
  pkg/apis/shipper/v1alpha1/zz_generated.defaults.go
  pkg/client/clientset/internalversion/clientset.go
  pkg/client/clientset/internalversion/doc.go
  pkg/client/clientset/internalversion/fake/clientset_generated.go
  pkg/client/clientset/internalversion/fake/doc.go
  pkg/client/clientset/internalversion/fake/register.go
  pkg/client/clientset/internalversion/scheme/doc.go
  pkg/client/clientset/internalversion/scheme/register.go
  pkg/client/clientset/internalversion/typed/shipper/internalversion/doc.go
  pkg/client/clientset/internalversion/typed/shipper/internalversion/fake/doc.go
  pkg/client/clientset/internalversion/typed/shipper/internalversion/fake/fake_shipper_client.go
  pkg/client/clientset/internalversion/typed/shipper/internalversion/generated_expansion.go
  pkg/client/clientset/internalversion/typed/shipper/internalversion/shipper_client.go
Labels: enhancement

#177 Migrate away from glog to klog
  cmd/shipper-state-metrics/collector.go
  cmd/shipper-state-metrics/main.go
  cmd/shipper/main.go
  go.mod
  pkg/chart/repo/repo.go
  pkg/chart/unmarshal.go
  pkg/clusterclientstore/queue.go
  pkg/clusterclientstore/store.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_utils.go
  pkg/controller/capacity/capacity_controller.go
  pkg/controller/capacity/deployment.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installer.go
  pkg/controller/janitor/janitor_controller.go
  pkg/controller/release/application.go
  pkg/controller/release/executor.go
  pkg/controller/release/release_controller.go
  pkg/controller/release/scheduler.go
  pkg/controller/rolloutblock/rolloutblock_controller.go
  pkg/controller/traffic/traffic_controller.go
  pkg/errors/errors.go
  pkg/errors/kubeclient.go
  pkg/metrics/prometheus/restclient.go
  pkg/webhook/webhook.go
  test/e2e/e2e_test.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
Labels: enhancement

#173 collector: don't group releases per cluster
  cmd/shipper-state-metrics/collector.go
Labels: enhancement

#168 Updated Application spec in docs with chart ranges
  docs/api-reference/porcelain/application.rst
  docs/examples/application-minimal.yaml
  docs/examples/application.yaml
Labels: documentation

#182 Shipper in 5 minutes doc: curl latest shipper.deployment.yaml fixes #130
  docs/start/install.rst
Labels: documentation

#181 crds: additional printer columns for Application
  crd/Application-crd.yaml
  pkg/crds/application.go
Labels: enhancement

#136 Replaced ghodss/yaml with community-supported sigs.k8s.io/yaml
  cmd/shipperctl/cmd/apply.go
  go.mod
  go.sum
  pkg/chart/repo/repo.go
  pkg/controller/capacity/builder/report_test.go
  pkg/testing/util.go
Labels: enhancement

#183 installer: read ReleaseLabel if InstallationTargetOwnerLabel is missing
  pkg/controller/installation/installer.go
Labels: bug

#179 Application controller exposes chart resolution issues
  pkg/conditions/constants.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
Labels: enhancement

#166 ReleaseController application picks the tip of the release chain as contender
  pkg/chart/repo/catalog.go
  pkg/chart/repo/repo.go
  pkg/chart/repo/repo_test.go
  pkg/controller/release/application.go
  pkg/controller/release/release_controller.go
  pkg/controller/release/release_controller_test.go
  pkg/controller/release/scheduler.go
  pkg/controller/release/scheduler_test.go
  pkg/util/application/releases.go
Labels: bug

#178 Release controller exposes executor problems fixes #174
  pkg/conditions/constants.go
  pkg/controller/release/application.go
  pkg/controller/release/release_controller_test.go
Labels: enhancement

#184 Composed a changelog file for v0.6.0
  CHANGELOG-0.6.md
Labels: documentation

#135 Give more information for errors of failed chart repo index
  pkg/chart/repo/repo.go
  pkg/errors/chart.go
Labels: enhancement

#187 shipper-state-metrics: initialize rolloutblocks lister
  cmd/shipper-state-metrics/main.go
Labels: bug

#191 Replaced addressing of the last element in Application.additionalPrin…
  crd/Application-crd.yaml
  pkg/crds/application.go
Labels: bug

#180 Improved amortised performance of repo.Fetch()
  pkg/chart/repo/repo.go
Labels: enhancement

#188 installation controller: also migrate CanOverride
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/installation/utils_test.go
Labels: bug

#193 Revert Application.additionalPrinterColumns from -1 to @length-1
  crd/Application-crd.yaml
  pkg/crds/application.go
Labels: bug

#167 docs: value of enable-helm-release-workaround requires quotes
  docs/limitations.rst
Labels: documentation

#199 installation controller: remove migration scaffolding
  CHANGELOG-0.7.md
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/installation/installer.go
  pkg/controller/installation/utils_test.go
Labels: enhancement

#202 collector: collect releases per cluster
  cmd/shipper-state-metrics/collector.go
Labels: bug

#201 kubernetes: improve shipper's deployments
  Dockerfile.shipper
  Dockerfile.shipper-state-metrics
  kubernetes/shipper-state-metrics.deployment.yaml
  kubernetes/shipper.deployment.yaml
Labels: enhancement
